# Generated by Django 5.1.7 on 2025-04-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='auto_generate',
            field=models.BooleanField(default=True, help_text='Automatically generate content when topic is provided'),
        ),
    ]
